-   id: check-commit-message
    name: check-commit-message
    entry: ./commiterator.sh check
    language: script
    pass_filenames: false
    stages: [commit-msg]
-   id: prepend-commit-message
    name: prepend-commit-message
    entry: ./commiterator.sh prepend
    language: script
    pass_filenames: false
    stages: [prepare-commit-msg]
-   id: verify-commit-signature
    name: verify-commit-signature
    entry: ./commiterator.sh verify
    language: script
    always_run: true
    pass_filenames: false
    stages: [post-commit, push]
