-   id: check-commit-message
    name: check-commit-message
    entry: ./commit_message.sh check
    language: script
    pass_filenames: false
-   id: prepend-commit-message
    name: prepend-commit-message
    entry: ./commit_message.sh prepend
    language: script
    pass_filenames: false
